name: ci-docker-wait-for-it
on:
  pull_request:
    branches:
      - main
jobs:
  check-application:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
      - run: docker compose run -d database
      - run: docker compose run -u root -d -p 8080:3000 app
      - name: Waiting environment to be ready
        run: wget -qO- https://raw.githubusercontent.com/eficode/wait-for/v2.1.3/wait-for | sh -s -- http://localhost:8080/ -- echo success
      - run: docker compose exec -T app bash -c "npm run test"

      # - name: SonarCloud Scan
      #   uses: SonarSource/sonarcloud-github-action@master
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
      #     SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

      - name: Set up QEMU # responsável por rodar o Docker em diversas arquiteturas
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx # responsável por fazer o build do Dockerfile
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub # Realiza o login em nossa conta do Dockerhub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Build and push # Neste step ele faz o build e o push(se estiver true) para o dockerhub

        uses: docker/build-push-action@v3
        with:
          push: true
          tags: brcwalkers/docker-wait-for-it:latest